# Generated by Django 4.2.23 on 2025-06-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellidos',
            field=models.CharField(default='ApellidoDesconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='carnet',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='carrera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ciclo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombres',
            field=models.CharField(default='ApellidoDesconocido', max_length=50),
        ),
    ]
