# Generated by Django 4.2.23 on 2025-06-23 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('biseccion', 'Bisección'), ('richardson', 'Extrapolación de Richardson')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('funcion', models.TextField(blank=True, null=True)),
                ('xl', models.FloatField(blank=True, null=True)),
                ('xu', models.FloatField(blank=True, null=True)),
                ('ea', models.FloatField(blank=True, null=True)),
                ('expr', models.TextField(blank=True, null=True)),
                ('x_val', models.FloatField(blank=True, null=True)),
                ('h_val', models.FloatField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_calculos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
